### ISSUE TITLE
Default selections for corpus-specific subsets

### ISSUE THREAD

**Issue by mmcauliffe** [MontrealCorpusTools/polyglot-server#19] opened 2018-07-20 18:06 UTC
In the Create phone subset interface, on the right hand side there should be buttons for pre-selecting sets of segments that have been hardcoded for SPADE datasets.  This would be "syllabics", "sibilants" and "stressed_vowels", which would give the user the ability to review these, make changes, etc, before saving.  Also, clicking these should change the subset label to "syllabic", "sibilant" or "stressed_vowel" respectively.

See the yaml files in the SPADE repo for these default selections (i.e., https://github.com/MontrealCorpusTools/SPADE/blob/master/ICECAN/ICECAN.yaml).

**Comment by msonderegger** [comment] 2018-07-24 20:00
This didn't work when I just tried it for ICE-Can -- I can push the "syllabic" button but nothing got added. Should it work?

**Comment by MichaelGoodale** [comment] 2018-07-25 14:14
Yeah it should, hmm, seems to be a problem with how it was merged.

**Comment by msonderegger** [comment] 2018-07-25 14:18
OK @MichaelGoodale you're on it?

Something else here (is this in another issue?) is that if these subsets aren't pre-defined in YAML the buttons to encode "syllabic" etc. shouldn't work (be greyed out?)

**Closed** 2018-07-25 16:35 UTC
Labels: UI, enhancement, enrichment

**Comment by msonderegger** [comment] 2018-07-26 14:39
FYI this is still an issue for Buckeye (on Jul 26) on roquefort.. 
![screen shot 2018-07-26 at 10 39 06 am](https://user-images.githubusercontent.com/798417/43269096-2494c3b6-90c0-11e8-94c5-8169a6d110a4.png)


syllabics not defined (I assume) but buttons not greyed out.

**Comment by msonderegger** [comment] 2018-07-26 14:40
I'll reopen this, but just re-close it if the issue is just Roquefort version is out-of-date
